// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/balance": {
            "get": {
                "description": "Retrieves balances for a comma-separated list of addresses",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Balance"
                ],
                "summary": "Get balances for multiple addresses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of addresses",
                        "name": "addresses",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/balance/{address}": {
            "get": {
                "description": "Retrieves the MNEE balance for a specific wallet address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Balance"
                ],
                "summary": "Get balance for a single address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/transaction": {
            "get": {
                "description": "Retrieves transaction history for one or more addresses with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History"
                ],
                "summary": "Get transaction history for multiple addresses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of Wallet Addresses",
                        "name": "addresses",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Starting score (default 0)",
                        "name": "fromScore",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/transaction/submit-rawtx": {
            "post": {
                "description": "Submits a pre-signed raw transaction string.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transfer"
                ],
                "summary": "Submit Raw Transaction",
                "parameters": [
                    {
                        "description": "Raw Hex",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RawTxRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/transaction/transfer": {
            "post": {
                "description": "Executes a transfer using multiple WIFs (if needed) and waits for cosigner response. Returns final TxID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transfer"
                ],
                "summary": "Synchronous Transfer",
                "parameters": [
                    {
                        "description": "Transfer Parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/transaction/transfer-async": {
            "post": {
                "description": "Executes a transfer using multiple WIFs (if needed) and returns a ticket ID immediately for polling.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transfer"
                ],
                "summary": "Asynchronous Transfer",
                "parameters": [
                    {
                        "description": "Transfer Parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/utxos/paginated/{address}": {
            "get": {
                "description": "Retrieves paginated unspent transaction outputs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTXO"
                ],
                "summary": "Get paginated UTXOs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 10)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/utxos/{address}/all": {
            "get": {
                "description": "Retrieves all unspent transaction outputs for an address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UTXO"
                ],
                "summary": "Get all UTXOs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.RawTxRequest": {
            "type": "object",
            "required": [
                "rawTxHex"
            ],
            "properties": {
                "rawTxHex": {
                    "type": "string",
                    "example": "01000000..."
                }
            }
        },
        "handlers.TransferRequest": {
            "type": "object",
            "required": [
                "request",
                "wifs"
            ],
            "properties": {
                "request": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "address",
                            "amount"
                        ],
                        "properties": {
                            "address": {
                                "type": "string",
                                "example": "1G6CB3Ch4zFkPmuhZzEyChQmrQPfi86qk3"
                            },
                            "amount": {
                                "type": "number",
                                "example": 0.1
                            }
                        }
                    }
                },
                "wifs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "L1dRKo...",
                        "K2..."
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "MNEE SDK API Wrapper (Go)",
	Description:      "A high-performance Golang REST API wrapper for the MNEE Golang SDK.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
